title: XiNGRZ's
permalink: /:year/:year-:month-:day/:title.html

exclude: [ ".gitignore", "README.md", "CNAME" ]
markdown: kramdown
highlighter: pygments

url: "http://xingrz.us"

disqus_short_name: 'xingrz'

google_tracking_id: 'UA-25258167-6'
